menu:
# - {name: 'reading list', url: '/reading'}
- {name: 'film and photo', url: '/media'}
- {name: 'resume', url: '/resume'}
- {name: 'contact', url: '/contact'}


social:
- {icon: 'github', link: 'https://github.com/shentopher'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/chrshen'}